name: barras
description: A simple and customizable barcode scanning package for Android and iOS. It uses AVCaptureSession in iOS and ZXing in Android.
version: 0.1.1-nullsafety.2
homepage: https://github.com/deadblit/barras
publish_to: none

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

  qrcode_forked:
    git: https://github.com/shaxxx/qrcode_forked
  torch_controller: ^2.0.1
  flutter_beep: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
